### ISSUE TITLE
License update

### ISSUE THREAD

**Issue by asd08573064** [FSoft-AI4Code/RepoHyper#4]
Dear Authors,

Thanks for the great effort!
I found the code 
[parse_source_code.py](https://github.com/FSoft-AI4Code/RepoHyper/blob/main/src/repo_graph/parse_source_code.py)
[repo_to_graph.py](https://github.com/FSoft-AI4Code/RepoHyper/blob/main/src/repo_graph/repo_to_graph.py)
super useful for my project, but there is no public license declaration. Could you update the license?

Thanks!

**Comment by bdqnghi** [comment]
thanks for asking ! We updated the MIT license.

**Comment by asd08573064** [comment]
Thanks for the update!
